chore: fixing cicd

diff --git a/.github/workflows/branch_build.yml b/.github/workflows/branch_build.yml
--- a/.github/workflows/branch_build.yml
+++ b/.github/workflows/branch_build.yml
@@ -46,6 +46,75 @@ jobs:
         echo "/usr/local/kubebuilder/bin" >> $GITHUB_PATH
     - name: Test
       run: make test
+  images:
+    name: Build Images
+    needs:
+    - test
+    runs-on: ubuntu-20.04
+    defaults:
+      run:
+        shell: bash
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v2
+    - name: Install Go
+      uses: actions/setup-go@v2
+      with:
+        go-version: 1.15.11
+    - name: Set up QEMU
+      uses: docker/setup-qemu-action@v1
+    - id: buildx
+      name: Set up docker buildx
+      uses: docker/setup-buildx-action@v1
+    - name: Cache Go modules
+      uses: actions/cache@v2
+      with:
+        path: ~/go/pkg/mod
+        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
+        restore-keys: ${{ runner.os }}-1.15.11-go-
+    - name: Install Kubebuilder
+      run: |-
+        os=$(go env GOOS)
+        arch=$(go env GOARCH)
+
+        # download kubebuilder and extract it to tmp
+        curl -L https://go.kubebuilder.io/dl/2.3.1/${os}/${arch} | tar -xz -C /tmp/
+
+        # move to a long-term location and put it on your path
+        # (you'll need to set the KUBEBUILDER_ASSETS env var if you put it somewhere else)
+        sudo mv /tmp/kubebuilder_2.3.1_${os}_${arch} /usr/local/kubebuilder
+        echo "/usr/local/kubebuilder/bin" >> $GITHUB_PATH
+    - name: Install operatorsdk
+      run: |-
+        export ARCH=$(case $(arch) in x86_64) echo -n amd64 ;; aarch64) echo -n arm64 ;; *) echo -n $(arch) ;; esac)
+        export OS=$(uname | awk '{print tolower($0)}')
+        export OPERATOR_SDK_DL_URL=https://github.com/operator-framework/operator-sdk/releases/latest/download
+        curl -LO ${OPERATOR_SDK_DL_URL}/operator-sdk_${OS}_${ARCH}
+        curl -LO ${OPERATOR_SDK_DL_URL}/checksums.txt
+        curl -LO ${OPERATOR_SDK_DL_URL}/checksums.txt.asc
+        grep operator-sdk_${OS}_${ARCH} checksums.txt | sha256sum -c -
+        chmod +x operator-sdk_${OS}_${ARCH} && sudo mv operator-sdk_${OS}_${ARCH} /usr/local/bin/operator-sdk
+        curl -LO https://github.com/operator-framework/operator-registry/releases/download/v1.15.3/${OS}-${ARCH}-opm
+        chmod +x ${OS}-${ARCH}-opm && sudo mv ${OS}-${ARCH}-opm /usr/local/bin/opm
+    - name: Install YQ
+      run: sudo snap install yq
+    - name: Login to Docker Hub
+      uses: docker/login-action@v1
+      with:
+        registry: quay.io/rh-marketplace
+        username: ${{secrets['quayUser']}}
+        password: ${{secrets['quayPassword']}}
+    - id: build
+      name: Build images
+      run: make clean-licenses save-licenses ${{ matrix.project }}/docker-build
+    strategy:
+      matrix:
+        project:
+        - base
+        - operator
+        - authchecker
+        - metering
+        - reporter
   deploy:
     name: Deploy
     needs:
@@ -57,6 +126,8 @@ jobs:
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
+      with:
+        fetch-depth: 0
     - name: Install Go
       uses: actions/setup-go@v2
       with:
@@ -114,17 +185,20 @@ jobs:
         if [[ "$GITHUB_REF" == *"refs/head/release"* ||  "$GITHUB_REF" == *"refs/head/hotfix"* ]] ; then
         echo "IS_DEV=false" >> $GITHUB_ENV
         fi
-    - id: build
-      name: Build images
-      run: make clean-licenses save-licenses docker-build
+
+        go get github.com/caarlos0/svu
+        echo "VERSION=$(svu minor)" >> $GITHUB_ENV
+
+        if [[ "$VERSION" == "" ]]; then
+        echo "failed to find version"
+        exit 1
+        fi
     - id: bundle
       name: Build bundle
       run: |-
-        go get github.com/caarlos0/svu
-        echo "building $BRANCH with dev=$IS_DEV"
+        echo "building $BRANCH with dev=$IS_DEV and version=$VERSION"
 
         cd v2
-        export VERSION=$(svu minor)
         export TAG=${VERSION}-${DEPLOY_SHA}
 
         echo "::group::Make Stable Bundle"
