fix: removing outdated images

diff --git a/.github/workflows/branch_build.yml b/.github/workflows/branch_build.yml
--- a/.github/workflows/branch_build.yml
+++ b/.github/workflows/branch_build.yml
@@ -15,10 +15,6 @@ jobs:
   test:
     name: Test
     runs-on: ubuntu-20.04
-    outputs:
-      version: ${{ steps.version.outputs.version }}
-      isDev: ${{ steps.version.outputs.isDev }}
-      tag: ${{ steps.version.outputs.tag }}
     defaults:
       run:
         shell: bash
@@ -59,47 +55,6 @@ jobs:
         echo "/usr/local/kubebuilder/bin" >> $GITHUB_PATH
     - name: Test
       run: make operator/test
-    - id: version
-      name: Get Version
-      run: |-
-        make svu
-        export VERSION="$(./bin/svu next --prefix '')"
-
-        if [ "$REF" == "" ]; then
-        	REF="$GITHUB_REF"
-        fi
-
-        if [[ "$GITHUB_HEAD_REF" != "" ]]; then
-        	echo "Request is a PR $GITHUB_HEAD_REF is head; is base $GITHUB_BASE_REF is base"
-          REF="$GITHUB_HEAD_REF"
-        fi
-
-        echo "Found ref $REF"
-
-        if [[ "$VERSION" == "" ]]; then
-          echo "failed to find version"
-          exit 1
-        fi
-
-        if [[ "$REF" == *"release"* ||  "$REF" == *"hotfix"* ]] ; then
-        echo "using release version and github_run_number"
-        export TAG="${VERSION}-${GITHUB_RUN_NUMBER}"
-        export IS_DEV="false"
-        else
-        echo "using beta in version"
-        export TAG="${VERSION}-beta-${GITHUB_RUN_NUMBER}"
-        export IS_DEV="true"
-        fi
-
-        echo "Found version $VERSION"
-        echo "::set-output name=version::$VERSION"
-        echo "VERSION=$VERSION" >> $GITHUB_ENV
-        echo "Found tag $TAG"
-        echo "TAG=$TAG" >> $GITHUB_ENV
-        echo "::set-output name=tag::$TAG"
-        echo "IS_DEV=$IS_DEV" >> $GITHUB_ENV
-        echo "::set-output name=isDev::$IS_DEV"
-        echo "REF=$REF" >> $GITHUB_ENV
   matrix-test:
     name: Matrix Test
     runs-on: ubuntu-20.04
@@ -146,11 +101,8 @@ jobs:
         - tests
   images:
     name: Build Images
-    needs:
-    - test
     runs-on: ubuntu-20.04
     env:
-      VERSION: ${{ needs.test.outputs.tag }}
       GO_VERSION: 1.16.8
     defaults:
       run:
@@ -194,26 +146,65 @@ jobs:
         # (you'll need to set the KUBEBUILDER_ASSETS env var if you put it somewhere else)
         sudo mv /tmp/kubebuilder_${version}_${os}_${arch} /usr/local/kubebuilder
         echo "/usr/local/kubebuilder/bin" >> $GITHUB_PATH
-    - name: Install YQ
-      run: sudo snap install yq
     - name: Login to Docker Hub
       uses: docker/login-action@v1
       with:
         registry: quay.io/rh-marketplace
         username: ${{secrets['quayUser']}}
         password: ${{secrets['quayPassword']}}
+    - id: version
+      name: Get Version
+      run: |-
+        make svu
+        export VERSION="$(./bin/svu next --prefix '')"
+
+        if [ "$REF" == "" ]; then
+        	REF="$GITHUB_REF"
+        fi
+
+        if [[ "$GITHUB_HEAD_REF" != "" ]]; then
+        	echo "Request is a PR $GITHUB_HEAD_REF is head; is base $GITHUB_BASE_REF is base"
+        	REF="$GITHUB_HEAD_REF"
+        fi
+
+        echo "Found ref $REF"
+
+        if [[ "$VERSION" == "" ]]; then
+        	echo "failed to find version"
+        	exit 1
+        fi
+
+        if [[ "$REF" == *"release"* ||  "$REF" == *"hotfix"* || "$REF" == *"refs/head/master"* || "$REF" == *"refs/head/develop"* ]] ; then
+        echo "using release version and github_run_number"
+        export TAG="${VERSION}-${GITHUB_RUN_NUMBER}"
+        export IS_DEV="false"
+        else
+        echo "using beta in version"
+        export VERSION=${VERSION}-beta.${GITHUB_RUN_NUMBER}
+        export TAG="${VERSION}-beta-${GITHUB_RUN_NUMBER}"
+        export IS_DEV="true"
+        fi
+
+        echo "Found version $VERSION"
+        echo "::set-output name=version::$VERSION"
+        echo "VERSION=$VERSION" >> $GITHUB_ENV
+        echo "Found tag $TAG"
+        echo "TAG=$TAG" >> $GITHUB_ENV
+        echo "::set-output name=tag::$TAG"
+        echo "IS_DEV=$IS_DEV" >> $GITHUB_ENV
+        echo "::set-output name=isDev::$IS_DEV"
+        echo "REF=$REF" >> $GITHUB_ENV
     - id: build
-      name: Build images
-      run: make clean-licenses save-licenses ${{ matrix.project }}/docker-build
+      name: Build and push images
+      run: |-
+        if [ "$IS_DEV" == "true" ]; then
+        	export ARCHS="amd64"
+        fi
+
+        make clean-licenses save-licenses ${{ matrix.project }}/docker-build
       env:
         DOCKERBUILDXCACHE: /tmp/.buildx-cache
-        IMAGE_PUSH: "false"
-    - id: push
-      name: Push images
-      run: make ${{ matrix.project }}/docker-build
-      env:
-        DOCKERBUILDXCACHE: /tmp/.buildx-cache
-        PUSH: "true"
+        IMAGE_PUSH: "true"
     strategy:
       matrix:
         project:
@@ -239,10 +230,6 @@ jobs:
       isDev: ${{ steps.bundle.outputs.isDev }}
       version: ${{ steps.bundle.outputs.version }}
       tag: ${{ steps.bundle.outputs.tag }}
-    env:
-      VERSION: ${{ needs.test.outputs.version }}
-      IMAGE_TAG: ${{ needs.test.outputs.tag }}
-      IS_DEV: ${{ needs.test.outputs.isDev }}
     defaults:
       run:
         shell: bash
@@ -285,14 +272,54 @@ jobs:
         # (you'll need to set the KUBEBUILDER_ASSETS env var if you put it somewhere else)
         sudo mv /tmp/kubebuilder_${version}_${os}_${arch} /usr/local/kubebuilder
         echo "/usr/local/kubebuilder/bin" >> $GITHUB_PATH
-    - name: Install YQ
-      run: sudo snap install yq
     - name: Login to Docker Hub
       uses: docker/login-action@v1
       with:
         registry: quay.io/rh-marketplace
         username: ${{secrets['quayUser']}}
         password: ${{secrets['quayPassword']}}
+    - id: version
+      name: Get Version
+      run: |-
+        make svu
+        export VERSION="$(./bin/svu next --prefix '')"
+
+        if [ "$REF" == "" ]; then
+        	REF="$GITHUB_REF"
+        fi
+
+        if [[ "$GITHUB_HEAD_REF" != "" ]]; then
+        	echo "Request is a PR $GITHUB_HEAD_REF is head; is base $GITHUB_BASE_REF is base"
+        	REF="$GITHUB_HEAD_REF"
+        fi
+
+        echo "Found ref $REF"
+
+        if [[ "$VERSION" == "" ]]; then
+        	echo "failed to find version"
+        	exit 1
+        fi
+
+        if [[ "$REF" == *"release"* ||  "$REF" == *"hotfix"* || "$REF" == *"refs/head/master"* || "$REF" == *"refs/head/develop"* ]] ; then
+        echo "using release version and github_run_number"
+        export TAG="${VERSION}-${GITHUB_RUN_NUMBER}"
+        export IS_DEV="false"
+        else
+        echo "using beta in version"
+        export VERSION=${VERSION}-beta.${GITHUB_RUN_NUMBER}
+        export TAG="${VERSION}-beta-${GITHUB_RUN_NUMBER}"
+        export IS_DEV="true"
+        fi
+
+        echo "Found version $VERSION"
+        echo "::set-output name=version::$VERSION"
+        echo "VERSION=$VERSION" >> $GITHUB_ENV
+        echo "Found tag $TAG"
+        echo "TAG=$TAG" >> $GITHUB_ENV
+        echo "::set-output name=tag::$TAG"
+        echo "IS_DEV=$IS_DEV" >> $GITHUB_ENV
+        echo "::set-output name=isDev::$IS_DEV"
+        echo "REF=$REF" >> $GITHUB_ENV
     - id: bundle
       name: Build bundle
       run: |-
@@ -316,6 +343,8 @@ jobs:
         echo "::set-output name=isDev::$IS_DEV"
         echo "::set-output name=version::$VERSION"
         echo "::set-output name=tag::$TAG"
+      env:
+        IMAGE_TAG: ${{ steps.version.outputs.tag }}
     - uses: actions/upload-artifact@v2
       with:
         name: release-bundle-${{ steps.bundle.outputs.tag }}
diff --git a/.github/workflows/release_status.yml b/.github/workflows/release_status.yml
--- a/.github/workflows/release_status.yml
+++ b/.github/workflows/release_status.yml
@@ -101,22 +101,23 @@ jobs:
 
         if [[ "$GITHUB_HEAD_REF" != "" ]]; then
         	echo "Request is a PR $GITHUB_HEAD_REF is head; is base $GITHUB_BASE_REF is base"
-          REF="$GITHUB_HEAD_REF"
+        	REF="$GITHUB_HEAD_REF"
         fi
 
         echo "Found ref $REF"
 
         if [[ "$VERSION" == "" ]]; then
-          echo "failed to find version"
-          exit 1
+        	echo "failed to find version"
+        	exit 1
         fi
 
-        if [[ "$REF" == *"release"* ||  "$REF" == *"hotfix"* ]] ; then
+        if [[ "$REF" == *"release"* ||  "$REF" == *"hotfix"* || "$REF" == *"refs/head/master"* || "$REF" == *"refs/head/develop"* ]] ; then
         echo "using release version and github_run_number"
         export TAG="${VERSION}-${GITHUB_RUN_NUMBER}"
         export IS_DEV="false"
         else
         echo "using beta in version"
+        export VERSION=${VERSION}-beta.${GITHUB_RUN_NUMBER}
         export TAG="${VERSION}-beta-${GITHUB_RUN_NUMBER}"
         export IS_DEV="true"
         fi
@@ -145,7 +146,7 @@ jobs:
           exit 1
         fi
 
-        status=$(echo $BRANCH_BUILD | jq -r '.status')
+        status=$(echo $BRANCH_BUILD | jq -r ' pffastatus')
         conclusion=$(echo $BRANCH_BUILD | jq -r '.conclusion')
 
         if [ "$status" != "completed" ] && [ "$conclusion" != "success" ]; then
